backend:
  name: git-gateway
  branch: main

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://codestitch.app/frontend/images/logo.png

media_folder: "src/assets/images/blog"
public_folder: "/assets/images/blog"
# publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "URL Slug",
          name: "url",
          widget: "string",
          hint: 'Specify where the page will be written to. If you use "Blog Post", the post will be accessible from "blog/blog-post"',
        }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "URL Slug",
          name: "url",
          widget: "string",
          hint: 'Specify where the page will be written to. If you use "Blog Post", the post will be accessible from "blog/blog-post"',
        }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime", required: false }
      - { label: "Tags", name: "tags", widget: "list", default: ["project"] }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Role", name: "role", widget: "list", required: false }
      - label: "Categories"
        name: "categories"
        widget: "list"
        default: ["branding", "web"]
        hint: "Add project categories like branding, web, etc."
      - { label: "Services", name: "services", widget: "list", required: false }
      - label: "Credits"
        name: "credits"
        widget: "list"
        fields: 
          - { label: "Credit", name: "credit", widget: "string", required: false }
      - { label: "Tools", name: "tools", widget: "list", required: false }
      - { label: 'Case Study', name: "body", widget: 'markdown', default: "Write your content here." }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Project Logo", name: "logo", widget: "image", required: false }
      - { label: "Background Image", name: "bg", widget: "image", required: false }
      - label: "Brand Process"
        name: "brand_process"
        widget: "list"
        fields: 
          - { label: "Image", name: "image", widget: "image" }
      - label: "Web Process"
        name: "web_process"
        widget: "list"
        fields: 
          - { label: "Image", name: "image", widget: "image" }
      - label: "Project Images"
        name: "project_images"
        widget: "list"
        fields: 
          - { label: "Image", name: "image", widget: "image" }
      - { label: "Website URL", name: "weburl", widget: "string", required: false }
      - { label: "Website Preview", name: "webpreview", widget: "image", required: false }
      - { label: "Mobile Preview", name: "mobilepreview", widget: "image", required: false }
      - { label: "Final Image", name: "fi", widget: "image", required: false }

