backend:
    name: git-gateway
    branch: main

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://codestitch.app/frontend/images/logo.png

media_folder: "src/assets/images/blog"
public_folder: "/assets/images/blog"
# publish_mode: editorial_workflow

collections:
    - name: "blog"
      label: "Blog"
      folder: "src/content/blog"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
                label: "URL Slug",
                name: "url",
                widget: "string",
                hint: 'Specify where the page will be written to. If you use "Blog Post", the post will be accessible from "blog/blog-post"',
            }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Author", name: "author", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
          - { label: "Featured Image", name: "image", widget: "image" }
          - { label: "Image Caption", name: "imageAlt", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
    - name: "projects"
      label: "Projects"
      folder: "src/content/projects"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
                label: "URL Slug",
                name: "url",
                widget: "string",
                hint: 'Specify where the page will be written to. If you use "Blog Post", the post will be accessible from "blog/blog-post"',
            }
          - { label: "Author", name: "author", widget: "string", required: false }
          - { label: "Date", name: "date", widget: "datetime", required: false }
          - { label: "Tags", name: "tags", widget: "list", default: ["project"] }
          - { label: "Services", name: "services", widget: "list",   field: {label: "service", name: "service", widget: "string"}, required: false}
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Description Image", name: "descriptionimage", widget: "image", required: false }
          - { label: 'Blog post content', name: 'body', widget: 'markdown' }
          - { label: "Featured Image", name: "image", widget: "image", required: false }
          - { label: "Background Image", name: "bg", widget: "image", required: false }
          - { label: "Project Overview", name: "overview", widget: "text" }
          - { label: "Project Image 1", name: "pi1", widget: "image", required: false }
          - { label: "Project Image 2", name: "pi2", widget: "image", required: false }
          - { label: "Role", name: "role", widget: "string", required: false }
          - { label: "Team", name: "team", widget: "string", required: false }
          - { label: "Branding", name: "branding", widget: "text", required: false }
          - { label: "Brand Image 1", name: "b1", widget: "image", required: false }
          - { label: "Brand Image 2", name: "b2", widget: "image", required: false }
          - { label: "Brand Image 3", name: "b3", widget: "image", required: false }
          - { label: "Brand Image 4", name: "b4", widget: "image", required: false }
          - { label: "Web Design", name: "webdesign", widget: "text", required: false }
          - { label: "WD Image 1", name: "wd1", widget: "image", required: false }
          - { label: "WD Image 2", name: "wd2", widget: "image", required: false }
          - { label: "WD Image 3", name: "wd3", widget: "image", required: false }
          - { label: "WD Image 4", name: "wd4", widget: "image", required: false }
          - { label: "Outcome", name: "outcome", widget: "text", required: false }
          - { label: "Final Image", name: "fi", widget: "image", required: false }
